#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

apt-get --allow-unauthenticated -y install mysql-client mysql-server

# Xenial provides mysql 5.7 which requires percona-xtrabackup-24
PXB_VERSION_OVERRIDE=24

# NOTE(lxkong): Refer to https://www.percona.com/doc/percona-xtrabackup/2.4/installation/apt_repo.html
wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
apt-get update
apt-get --allow-unauthenticated -y install percona-xtrabackup-${PXB_VERSION_OVERRIDE}

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off
show_compatibility_56 = on
_EOF_

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]
!includedir /etc/mysql/conf.d/
_EOF_

if [ -e /etc/init/mysql.conf ]; then
    rm -f /etc/init/mysql.conf
fi

# Allow mysql user to execute ip command without password, this is needed in
# mysql systemd service profile.
cat <<EOF > /etc/sudoers.d/60_mysql
mysql ALL=(ALL) NOPASSWD: /sbin/ip
EOF

# Re-define mysql systemd service definition
cat <<EOF > /etc/systemd/system/mysql.service
[Unit]
Description=MySQL Community Server
After=network-online.target datastore-netns.service
Requires=datastore-netns.service

[Install]
WantedBy=multi-user.target

[Service]
User=mysql
Group=mysql
PermissionsStartOnly=true
ExecStartPre=/sbin/ip netns exec datastore /usr/share/mysql/mysql-systemd-start pre
ExecStart=/bin/bash -c 'sudo /sbin/ip netns exec datastore /usr/sbin/mysqld --user=mysql'
ExecStartPost=/sbin/ip netns exec datastore /usr/share/mysql/mysql-systemd-start post
TimeoutSec=300
Restart=on-failure
RuntimeDirectory=mysqld
EOF
